storage:
  storageLocations:
    default: D:\DataSSD\Imker\Data
update:
  updateCheckInterval: 10
endpoints:
  simpleWeatherVariables:
    - Temperature2m
    - WindSpeed10m
models:
  definedModels:
    0:
      meta:
        name: INCA
        friendlyName: INCA
        copyright: GeoSphere Austria under CC BY-SA 4.0
      receiver:
        receiverName: ftpSingleFile
        parserName: netcdf
      source:
        ftpHost: eaftp.zamg.ac.at
        ftpSubFolder: nowcast
        prefix: nowcast_
        postfix: .nc
        dateFormat: yyyyMMddHHmm
        updateFrequency: PT15M
      mapping:
        variableMapping:
          WindDirection10m: DD
          WindSpeed10m: FF
          GustSpeed10m: FX
          RelativeHumidity2m: RH
          PrecipitationSum: RR
          DewPoint: TD
          Temperature2m: TT
        unitMapperFile: src/test/resources/unit_map.csv
      storage:
        storageLocationName: default
        subFolderName: inca
        policy:
          maxFiles: 1
          maxAge: PT30M
      cache:
        variablesInMemory:
          - WindDirection10m
          - WindSpeed10m
          - GustSpeed10m
          - RelativeHumidity2m
          - PrecipitationSum
          - DewPoint
          - Temperature2m
    1:
      meta:
        name: AROME
        friendlyName: AROME
        copyright: GeoSphere Austria under CC BY-SA 4.0
      receiver:
        receiverName: ftpSingleFile
        parserName: netcdf
      source:
        ftpHost: eaftp.zamg.ac.at
        ftpSubFolder: nwp
        prefix: nwp_
        postfix: .nc
        dateFormat: yyyyMMddHH
        updateFrequency: PT3H
      mapping:
        variableMapperFile: src/test/resources/arome/arome_map.csv
        unitMapperFile: src/test/resources/unit_map.csv
      storage:
        storageLocationName: default
        subFolderName: arome
        policy:
          maxFiles: 1
      cache:
        variablesInMemory:
          - Temperature2m