storage:
  storageLocations:
    default: C:\Users\reall\Downloads\incadata
update:
  updateCheckInterval: 10
endpoints:
  simpleWeatherVariables:
    - Temperature2m
    - WindSpeed10m
models:
  definedModels:
    0:
      meta:
        name: INCA
        friendlyName: INCA
        copyright: GeoSphere Austria under CC BY-SA 4.0
      receiver:
        receiverName: ftpSingleFile
        parserName: netcdf
      source:
        ftpHost: eaftp.zamg.ac.at
        ftpSubFolder: nowcast
        prefix: nowcast_
        postfix: .nc
        dateFormat: yyyyMMddHHmm
        updateFrequency: PT15M
      mapping:
        variableMapperFile: src/test/resources/inca/inca_map.csv
        unitMapperFile: src/test/resources/unit_map.csv
      storage:
        storageLocationName: default
        subFolderName: inca
        policy:
          maxFiles: 1
          maxAge: PT30M
      cache:
        variablesInMemory:
          - WindDirection10m
          - WindSpeed10m
          - GustSpeed10m
          - RelativeHumidity2m
          - PrecipitationSum
          - DewPoint
          - Temperature2m
